[package]
name = "pattern_match"
version = "0.1.0"
authors = ["Wei Yang <richardw.yang@linux.intel.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
