apiVersion: v1
kind: Pod
metadata:
  name: nginx-app
  labels:
    run: nginx-app
spec:
  containers:
  - name: nginx
    env:
    - name: USER
      value: "test"
    image: nginx:latest
    ports:
    - containerPort: 80

