# General rule
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# rules_go
http_archive(
    name = "io_bazel_rules_go",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.22.2/rules_go-v0.22.2.tar.gz",
        "https://github.com/bazelbuild/rules_go/releases/download/v0.22.2/rules_go-v0.22.2.tar.gz",
    ],
    sha256 = "142dd33e38b563605f0d20e89d9ef9eda0fc3cb539a14be1bdb1350de2eda659",
)

load("@io_bazel_rules_go//go:deps.bzl", "go_rules_dependencies", "go_register_toolchains")

go_rules_dependencies()

go_register_toolchains()

# gazelle
http_archive(
    name = "bazel_gazelle",
    urls = [
        "https://storage.googleapis.com/bazel-mirror/github.com/bazelbuild/bazel-gazelle/releases/download/v0.20.0/bazel-gazelle-v0.20.0.tar.gz",
        "https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.20.0/bazel-gazelle-v0.20.0.tar.gz",
    ],
    sha256 = "d8c45ee70ec39a57e7a05e5027c32b1576cc7f16d9dd37135b0eddde45cf1b10",
)

load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies", "go_repository")

gazelle_dependencies()

# rules_docker
http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "5ec37b55cba408b9c9a72e07543a30b53a50feed6b135ed4b4184e543a0911c7",
    strip_prefix = "rules_docker",
    urls = [
        "https://github.com/RichardWeiYang/rules_docker/releases/download/v0.14.4-1/rules_docker-v0.14.4-1.tar.gz",
        # "http://localhost:8000/rules_docker-0.14.4.tar.gz",
    ],
)

load(
    "@io_bazel_rules_docker//repositories:repositories.bzl",
    container_repositories = "repositories",
)

container_repositories()

load("@io_bazel_rules_docker//repositories:deps.bzl", container_deps = "deps")

container_deps()

load("@io_bazel_rules_docker//repositories:pip_repositories.bzl", "pip_deps")

pip_deps()

load(
    "@io_bazel_rules_docker//go:image.bzl",
    _go_image_repos = "repositories",
)

_go_image_repos()

go_repository(
    name = "com_github_gorilla_mux",
    importpath = "github.com/gorilla/mux",
    sum = "h1:gnP5JzjVOuiZD07fKKToCAOjS0yOpj/qPETTXCCS6hw=",
    version = "v1.7.3",
)

load(
    "@io_bazel_rules_docker//container:container.bzl",
    "container_pull",
)

# Pull base image
container_pull(
    name = "shyw13",
    registry = "index.docker.io",
    repository = "shyw13/api_image",
    tag = "v0.1",
)
container_pull(
    name = "fedora",
    digest = "sha256:5e2b864cfe165fa7da6606b29a9e60549eb7cc9ae7fb574614110d1494b0f0c2",
    registry = "index.docker.io",
    repository = "library/fedora",
    tag = "31",
)
container_pull(
    name = "fedora_ppc64le",
    digest = "sha256:50ab81a4619f7e94793aba65f3a40505bdfb9b59dcf6ae6deb8f974723e966d9",
    puller_linux = "@go_puller_linux_ppc64le//file:downloaded",
    registry = "index.docker.io",
    repository = "library/fedora",
    tag = "31",
)

# configure private docker credential
# Load the macro that allows you to customize the docker toolchain configuration.
#load("@io_bazel_rules_docker//toolchains/docker:toolchain.bzl",
#    docker_toolchain_configure="toolchain_configure"
#)
#
#docker_toolchain_configure(
#  name = "docker_config",
#  # Replace this with an absolute path to a directory which has a custom docker
#  # client config.json. Note relative paths are not supported.
#  # Docker allows you to specify custom authentication credentials
#  # in the client configuration JSON file.
#  # See https://docs.docker.com/engine/reference/commandline/cli/#configuration-files
#  # for more details.
#  client_config="/home/richard/.docker/config.json",
#)
